In [1]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\Sahil Gautam\Downloads\Dataa1.csv")

In [6]:
df

,Row ID,Customer Name,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,@
0,1,Claire Gute,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,NaN
1,2,Claire Gute,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,NaN
2,3,Darrin Van Huff,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,NaN
3,4,Sean O'Donnell,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,NaN
4,5,Sean O'Donnell,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,Tom Boeckenhauer,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Consumer,United States,Miami,...,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,NaN
9990,9991,Dave Brooks,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Consumer,United States,Costa Mesa,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,NaN
9991,9992,Dave Brooks,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Consumer,United States,Costa Mesa,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,NaN
9992,9993,Dave Brooks,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Consumer,United States,Costa Mesa,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,NaN
9993,9994,Chris Cortes,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Consumer,United States,Westminster,...,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,NaN

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Customer Name  9994 non-null   object
 2   Order ID       9994 non-null   object
 3   Order Date     9994 non-null   object
 4   Ship Date      9994 non-null   object
 5   Ship Mode      9994 non-null   object
 6   Customer ID    9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  @              0 non-null      float64
dtypes: float64(4), int64(3), object(15)
memory usage: 1.7+ MB
None

In [9]:
print(df.head())

   Row ID    Customer Name        Order ID  Order Date   Ship Date  \
0       1      Claire Gute  CA-2016-152156   11/8/2016  11/11/2016
1       2      Claire Gute  CA-2016-152156   11/8/2016  11/11/2016
2       3  Darrin Van Huff  CA-2016-138688   6/12/2016   6/16/2016
3       4   Sean O'Donnell  US-2015-108966  10/11/2015  10/18/2015
4       5   Sean O'Donnell  US-2015-108966  10/11/2015  10/18/2015

        Ship Mode Customer ID    Segment        Country             City  ...  \
0    Second Class    CG-12520   Consumer  United States        Henderson  ...
1    Second Class    CG-12520   Consumer  United States        Henderson  ...
2    Second Class    DV-13045  Corporate  United States      Los Angeles  ...
3  Standard Class    SO-20335   Consumer  United States  Fort Lauderdale  ...
4  Standard Class    SO-20335   Consumer  United States  Fort Lauderdale  ...

  Region       Product ID         Category Sub-Category  \
0  South  FUR-BO-10001798        Furniture    Bookcases
1  South  FUR-CH-10000454        Furniture       Chairs
2   West  OFF-LA-10000240  Office Supplies       Labels
3  South  FUR-TA-10000577        Furniture       Tables
4  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600        2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400        3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200        2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775        5
4                     Eldon Fold 'N Roll Cart System   22.3680        2

   Discount    Profit   @
0      0.00   41.9136 NaN
1      0.00  219.5820 NaN
2      0.00    6.8714 NaN
3      0.45 -383.0310 NaN
4      0.20    2.5164 NaN

[5 rows x 22 columns]

In [10]:
df = df.drop_duplicates()

In [12]:
print(df.isnull().sum())

Row ID              0
Customer Name       0
Order ID            0
Order Date          0
Ship Date           0
Ship Mode           0
Customer ID         0
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Product ID          0
Category            0
Sub-Category        0
Product Name        0
Sales               0
Quantity            0
Discount            0
Profit              0
@                9994
dtype: int64

In [13]:
df = df.drop(columns=['@'])

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('[^a-z0-9_]', '', regex=True)

In [15]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [16]:
df['ship_date'] = pd.to_datetime(df['ship_date'], errors='coerce')

In [17]:
df = df.drop_duplicates()

In [18]:
df = df.dropna(subset=['order_date', 'ship_date'])

In [19]:
df.to_csv(r'C:\Users\Sahil Gautam\Downloads\cleaned_sales_data3.csv', index=False)